### ISSUE TITLE
Model converges at suboptimal revenue

### ISSUE THREAD

**Issue by degregat** [mechanism-learning-research/two-player-auctions#1]
## Problem
Preliminary training runs show that regret gets minimized while revenue gets maximized. Regret converges around 0, as it should, but revenue converges at around 50-60% of the values of the experiments from the paper.

## Approach
Maybe the model needs to be tuned, maybe it is the choice of hyperparameters. Further experiments are needed.

**Comment by degregat** [comment]
Since fixing the examples with 46cc3da01a4ccebfb5f8ecbe339cdf2626c3519a we achieve around 85% of the results from the paper with this [example](https://github.com/degregat/two-player-auctions/blob/46cc3da01a4ccebfb5f8ecbe339cdf2626c3519a/algnet.py#L492).

**Comment by undefdev** [comment]
I ran some experiments with a9b82d6.

The results from the paper are

| Bidder x Items | Revenue (Mean, Standard Deviation) | Regret (Mean, Standard Deviation) |
|---|---|---|
| 1x2 | (0.555, 0.0019) | (0.00055, 0.00014) |
| 1x10 | (3.487, 0.0135) | (0.00165, 0.00057) |
| 2x2 | (0.879, 0.0024) | (0.00058, 0.00023) |
| 3x10 | (5.562, 0.0308) | (0.00193, 0.00033) |
| 5x10 | (6.781, 0.0504) | (0.00385, 0.00043) |

The paper defines a score $\sqrt{\text{Revenue}} - \sqrt{\text{Regret}}$. Since during testing of our experiments we sometimes get negative regret, we use the score $\sqrt{\text{Revenue}} - \sqrt{\max(0,\text{Regret})}$ to compare models, such that it is well-defined. This however ignores how much the models break IR in practice.

Except for the 1x2-case, where the optimal auction is even known analytically, **the results do not reproduce**.
Interestingly, **our 2x2 auction consistently achieves a better score**, while slightly breaking IR, since test regret is negative.

Some reasons for this might be:

### bug in regret computation
The paper never lists negative regret in their experiments, and in section 4.1 of the paper they state that "by construction IR is respected". In our experiments regret is often negative during testing, in the 1-bidder 10-items case quite heavily so! This entails that IR can be broken in the learned auctions, which is undesired. We should check whether there is an error in the regret computation and think about whether it's reasonable to assume that IR cannot be broken during testing... At the moment I can't justify this assumption.

### The hyperparameters stated in the paper are incomplete or incorrect
The paper states that the following hyperparameters were used for the experiments:
    `net_depth`$\in [3, 7]$
    `net_width`$\in[50, 100, 200]$
    `learning_rate`$\in [0.001, 0.0005]$
    `num_steps`$\in [160000, 240000]$
    `misr_reinit_iv`$\in[800, 1600]$
    `misr_reinit_lim`$\in[40000, 60000]$
    `misr_updates`$=100$
    `num_test_samples`$=10000$

We refrained from running a complete grid search on these parameters, because it would have been too costly. However, given that bigger models have more expressive power that smaller models and given that the standard deviation for the published revenues and regrets have been small (even though they only took 5 samples!), it seems extremely unlikely that the current implementation can reproduce all of the papers results using a subset of these parameters.

The following experiments have been run on a Macbook Pro M1 Max 64gb:


|   Bidders |   Items |    Score |       Regret |      Revenue |   num_steps |   misr_reinit_iv |   misr_reinit_lim |   batch_size |   net_width |   net_depth |   learning_rate |   rng_seed_training |   rng_seed_test |
|----------:|--------:|---------:|-------------:|---------:|------------:|-----------------:|------------------:|-------------:|------------:|------------:|----------------:|--------------------:|----------------:|
|         1 |       2 | 0.721603 |  0.000984894 | 0.566988 |      160000 |              800 |             40000 |          500 |          50 |           7 |           0.001 |                1529 |            6266 |
|         1 |       2 | 0.697703 |  0.00186504  | 0.548917 |      160000 |              800 |             40000 |          500 |          50 |           3 |           0.001 |                5100 |            8298 |
|         1 |      10 | 2.23338  | -3.61913     | 4.98801  |      160000 |              800 |             40000 |          500 |          50 |           3 |           0.001 |                5100 |            8298 |
|         3 |      10 | 2.31859  | -0.000376015 | 5.37587  |      160000 |              800 |             40000 |          500 |         100 |           7 |           0.001 |                5100 |            8298 |
|         3 |      10 | 2.30926  | -0.0653015   | 5.33269  |      160000 |              800 |             40000 |          500 |          50 |           3 |           0.001 |                5100 |            8298 |
|         3 |      10 | 0.638808 |  2.8375      | 5.39771  |      160000 |              800 |             40000 |          500 |         100 |           7 |           0.001 |                1529 |            6266 |
|         5 |      10 | 2.40954  | -0.0331063   | 5.80589  |      160000 |              800 |             40000 |          500 |          50 |           7 |           0.001 |                5100 |            8298 |


These experiments have been run on a desktop pc with a NVIDIA GeForce RTX 3090:

|   Bidders |   Items |   Score |       Regret |   Revenue |   num_steps |   misr_reinit_iv |   misr_reinit_lim |   batch_size |   net_width |   net_depth |   learning_rate |   rng_seed_training |   rng_seed_test |
|----------:|--------:|--------:|-------------:|----------:|------------:|-----------------:|------------------:|-------------:|------------:|------------:|----------------:|--------------------:|----------------:|
|         2 |       2 | 1.07077 | -0.105464    |   1.14655 |      160000 |              800 |             40000 |          500 |         100 |           7 |          0.001  |                1529 |            6266 |
|         2 |       2 | 1.06192 | -0.0455345   |   1.12767 |      160000 |              800 |             40000 |          500 |         100 |           7 |          0.001  |                5100 |            8298 |
|         2 |       2 | 1.04154 | -0.0189652   |   1.0848  |      240000 |              800 |             40000 |          500 |         100 |           7 |          0.001  |                1529 |            6266 |
|         2 |       2 | 1.03726 | -0.0754253   |   1.07592 |      160000 |              800 |             40000 |          500 |          50 |           7 |          0.001  |                5100 |            8298 |
|         2 |       2 | 1.03175 | -0.0449141   |   1.06451 |      160000 |              800 |             40000 |          500 |          50 |           3 |          0.001  |                5100 |            8298 |
|         2 |       2 | 1.03175 | -0.0449141   |   1.06451 |      160000 |              800 |             40000 |          500 |          50 |           3 |          0.001  |                5100 |            8298 |
|         2 |       2 | 1.02523 | -0.0343708   |   1.05109 |      240000 |             1600 |             60000 |          500 |         200 |           7 |          0.001  |                5100 |            8298 |
|         2 |       2 | 1.02117 | -0.0196129   |   1.04278 |      160000 |              800 |             40000 |          500 |         200 |           7 |          0.001  |                5100 |            8298 |
|         2 |       2 | 1.01231 | -0.0387856   |   1.02478 |      240000 |             1600 |             60000 |          500 |         200 |           7 |          0.0005 |                5100 |            8298 |
|         2 |       2 | 1.00899 | -0.0722598   |   1.01806 |      240000 |             1600 |             60000 |          500 |         100 |           7 |          0.0005 |                5100 |            8298 |
|         5 |      10 | 2.41078 | -0.0111208   |   5.81184 |      240000 |             1600 |             60000 |          500 |         200 |           7 |          0.0005 |                1529 |            6266 |
|         5 |      10 | 2.3765  | -0.00218311  |   5.64774 |      240000 |             1600 |             60000 |          500 |         200 |           7 |          0.0005 |                5100 |            8298 |
|         5 |      10 | 2.36296 | -0.00392707  |   5.58357 |      160000 |              800 |             40000 |          500 |         100 |           7 |          0.001  |                1529 |            6266 |
|         5 |      10 | 2.36016 |  0.000116534 |   5.62144 |      240000 |              800 |             40000 |          500 |         200 |           7 |          0.001  |                1529 |            6266 |
|         5 |      10 | 2.28098 |  0.000470194 |   5.30225 |      240000 |             1600 |             60000 |          500 |         200 |           7 |          0.001  |                1529 |            6266 |

**Comment by undefdev** [comment]
As of 2f14e5a there was a fix wrt. the MLP configurations.
The current best scores are the following

| Bidder x Items | Mean Score | Our Best Score |
|----------------|------------|------------|
| 1x2            | 0.7215     | 0.7006 |
| 1x10           | 1.8267     | 1.8519 |
| 2x2            | 0.9135     | 1.0649 |
| 3x10           | 2.3145     | computing |
| 5x10           | 2.5420     | computing |
