### ISSUE TITLE
Run experiments with valuation misreporting

### ISSUE THREAD

**Issue by degregat** [mechanism-learning-research/two-player-auctions#6]
1. Test influence of manipulated valuation reports w/o DP
2. Test influence of manipulated valuation reports with DP:
  - online attack
  - offline attack
3. Compare these to baselines and baseline settings with DP

**Comment by undefdev** [comment]
Ran experiments and published results in [e0da218](https://github.com/mechanism-learning-research/two-player-auctions/commit/e0da2189a1ea89bbd78e5848e1817afac3dbaae8).

Omitted offline attack, since I didn't find distribution parameters for an offline attack yet that are even remotely as dangerous as in the online attack case. Furthermore the computations take quite long on my hardware :)
